module Application.Colors exposing ( colors, getColor, randomColor )

import Random
import Array exposing (Array, get, length, fromList)


randomColor : Random.Generator Int
randomColor =
  (Random.int 0 ((length colors) - 1 ))


getColor : Int -> String
getColor index =
  let
      color = get index colors
  in
     case color of
       Just color -> color
       Nothing -> "white"


colors : Array String
colors =
  fromList [ "aliceblue"
           , "antiquewhite"
           , "aqua"
           , "aquamarine"
           , "azure"
           , "beige"
           , "bisque"
           , "black"
           , "blanchedalmond"
           , "blue"
           , "blueviolet"
           , "brown"
           , "burlywood"
           , "cadetblue"
           , "chartreuse"
           , "chocolate"
           , "coral"
           , "cornflowerblue"
           , "cornsilk"
           , "crimson"
           , "cyan"
           , "darkblue"
           , "darkcyan"
           , "darkgoldenrod"
           , "darkgray"
           , "darkgreen"
           , "darkkhaki"
           , "darkmagenta"
           , "darkolivegreen"
           , "darkorange"
           , "darkorchid"
           , "darkred"
           , "darksalmon"
           , "darkseagreen"
           , "darkslateblue"
           , "darkslategray"
           , "darkturquoise"
           , "darkviolet"
           , "deeppink"
           , "deepskyblue"
           , "dimgray"
           , "dodgerblue"
           , "firebrick"
           , "floralwhite"
           , "forestgreen"
           , "fuchsia"
           , "gainsboro"
           , "ghostwhite"
           , "gold"
           , "goldenrod"
           , "gray"
           , "green"
           , "greenyellow"
           , "honeydew"
           , "hotpink"
           , "indianred"
           , "indigo"
           , "ivory"
           , "khaki"
           , "lavender"
           , "lavenderblush"
           , "lawngreen"
           , "lemonchiffon"
           , "lightblue"
           , "lightcoral"
           , "lightcyan"
           , "lightgoldenrodyellow"
           , "lightgray"
           , "lightgreen"
           , "lightpink"
           , "lightsalmon"
           , "lightseagreen"
           , "lightskyblue"
           , "lightslategray"
           , "lightsteelblue"
           , "lightyellow"
           , "lime"
           , "limegreen"
           , "linen"
           , "magenta"
           , "maroon"
           , "mediumaquamarine"
           , "mediumblue"
           , "mediumorchid"
           , "mediumpurple"
           , "mediumseagreen"
           , "mediumslateblue"
           , "mediumspringgreen"
           , "mediumturquoise"
           , "mediumvioletred"
           , "midnightblue"
           , "mintcream"
           , "mistyrose"
           , "moccasin"
           , "navajowhite"
           , "navy"
           , "oldlace"
           , "olive"
           , "olivedrab"
           , "orange"
           , "orangered"
           , "orchid"
           , "palegoldenrod"
           , "palegreen"
           , "paleturquoise"
           , "palevioletred"
           , "papayawhip"
           , "peachpuff"
           , "peru"
           , "pink"
           , "plum"
           , "powderblue"
           , "purple"
           , "rebeccapurple"
           , "red"
           , "rosybrown"
           , "royalblue"
           , "saddlebrown"
           , "salmon"
           , "sandybrown"
           , "seagreen"
           , "seashell"
           , "sienna"
           , "silver"
           , "skyblue"
           , "slateblue"
           , "slategray"
           , "snow"
           , "springgreen"
           , "steelblue"
           , "tan"
           , "teal"
           , "thistle"
           , "tomato"
           , "turquoise"
           , "violet"
           , "wheat"
           , "whitesmoke"
           , "yellow"
           , "yellowgreen" ]
